#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

if [[ -z ${1} ]]; then
	echo >&2 "USAGE: $0 concourse-target"
	exit 1
fi
concourse=${1}
fly_cmd="${FLY_CMD:-fly}"

manifest=$($fly_cmd -t $concourse get-pipeline -p docker-images)
promote_jobs=( $(spruce json <(echo "$manifest") | jq -r '.jobs[].name | select(startswith("promote"))') )

for promote in "${promote_jobs[@]}"; do
  $fly_cmd -t $concourse trigger-job -j docker-images/$promote
done
